### ISSUE TITLE
ТЫ ЧЁ ГНИДА ГДЕ МОНИТОРИНГ

### ISSUE THREAD

**Issue by UserCommon** [nnagibator228/Wirehole-Boosted#1]
чукча

**Comment by nnagibator228** [comment]
Здравствуйте, очень жаль, что Вы столкнулись с проблемой. 
Информация по тому, как получить доступ к каждой из графических консолей мониторинга доступна в [файле README в разделе FAQ](https://github.com/nnagibator228/Wirehole-Boosted#faq) для каждой из веток. Рекомендуется использовать сборку из ветки `/rproxy/` как самую актуальную. В случае возникновения трудностей, проверьте Ваши сетевые настройки.
Благодарю за обращение. Если возникнут еще вопросы - можете обращаться вновь. Если обнаружите неточность или ошибку, пожалуйста, сообщите мне для скорейшего устранения.

**Comment by UserCommon** [comment]
Ну лан
